### ISSUE TITLE
NSInvalidArgumentException: Application tried to present modally an active controller

### ISSUE THREAD

**Issue by pt7892** [zoontek/react-native-bootsplash#161]
# Bug report

## Summary

I've been seeing reports from sentry that show this error `NSInvalidArgumentException: Application tried to present modally an active controller`. Stack traces point to this line of code `-[RNBootSplash show:] node_modules/react-native-bootsplash/ios/RNBootSplash.m:102`. 

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 193.54 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/opt/node@12/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.2.5

## Steps to reproduce

I can't reproduce this issue locally, tried with simulator and physical device, but no luck. From what I understood, somehow this line of code is being called `[_presentedViewController presentViewController:_splashViewController animated:false completion:nil];`, while `_splashViewController` is already being shown. `_visible` flag should prevent this, but maybe, i guess, `presentViewController` or `dismissViewControllerAnimated` are called asynchronously.

Describe what you expected to happen:

Not to crash app

## Reproducible sample code

I don't have steps to reproduce, but I can show how I'm using this library to hide content of the app when user opens recent apps, or puts app in the background. I'm using this hook to listen to app state, and show/hide splash screen

```ts
import { useEffect } from 'react';
import { AppState } from 'react-native';
import RNBootSplash from 'react-native-bootsplash';

export default () => {
    useEffect(() => {
        const handleAppStateChange: Parameters<typeof AppState.addEventListener>[1] = (
            nextAppState
        ) => {
            if (['background', 'inactive'].includes(nextAppState)) {
                RNBootSplash.show();
            } else if (nextAppState === 'active') {
                RNBootSplash.hide({ duration: 250 });
            }
        };

        const setupAppStateChangeEventListener = () =>
            AppState.addEventListener('change', handleAppStateChange);

        setupAppStateChangeEventListener();
        return () => AppState.removeEventListener('change', handleAppStateChange);
    }, []);
};
```

Also, i have useEffect in the root of the app to hide splash screen on initial mount

```ts
    useEffect(() => {
        RNBootSplash.hide({ duration: 250 });
    }, []);
```

**Comment by zoontek** [comment]
@pt7892 This might be hard to reproduce. Could you try the `next` version? The API is now Promise based, it will be a lot harder to create race conditions 🙂

**Comment by pt7892** [comment]
Tried latest 3.0.1, but now app going to inactive or background state does not fire `RNBootSplash.show()`, and returning back to app raises error: `Error: A bootsplash task is already pending`


```ts
import { useEffect } from 'react';
import { AppState } from 'react-native';
import RNBootSplash from 'react-native-bootsplash';

export default () => {
    useEffect(() => {
        const handleAppStateChange: Parameters<typeof AppState.addEventListener>[1] = (
            nextAppState
        ) => {
            if (['background', 'inactive'].includes(nextAppState)) {
                RNBootSplash.show()
                    .then(() => console.log('fired show'))
                    .catch((e) => console.log('error show'));
            } else if (nextAppState === 'active') {
                RNBootSplash.hide({ fade: true })
                    .then(() => console.log('fired hide'))
                    .catch((e) => {
                        console.log('error hide');
                        console.log(e);
                    });
            }
        };

        const setupAppStateChangeEventListener = () =>
            AppState.addEventListener('change', handleAppStateChange);

        setupAppStateChangeEventListener();
        return () => AppState.removeEventListener('change', handleAppStateChange);
    }, []);
};
```

**Comment by zoontek** [comment]
@pt7892 Because you fire the function **twice** (`inactive`, and shortly after, `background`). That's precisely why the issue happen initially (check the `AppState` doc: https://reactnative.dev/docs/appstate)

In v2: `inactive` -> `show()` -> `background` -> `show()`. And sometimes the first hide wasn't completed yet (slow phones?), explaining the error.
In v3: `inactive` -> `show()` -> `background` -> ❌

I will do a quick check that everything is available to perform this in the new version.

**Comment by pt7892** [comment]
Ok, i tried what you suggested. Now when i use just one the state following happens:

`inactive` only:

`inactive` -> `show()` -> not showing splash screen -> go back to app -> `hide()` -> `Error: A bootsplash task is already pending`

`background` only:

`background` -> `show()` -> not showing spalsh screen -> go back to app -> splash screen shown -> `hide()` -> spasl screen gone

**Comment by zoontek** [comment]
Yes, I tried it too, I'm writing a fix to allow this 🙂

**Comment by pt7892** [comment]
Great, thanks a lot :)

**Comment by zoontek** [comment]
As this is a recurring wanted feature and using `AppState` is not perfect since the JS execution **might** be paused in some cases, I think about adding a new method + a hook:

- `setPrivateModeEnabled(boolean)`
- `usePrivateMode()` to protect some screens / some components (with a LIFO, similar to RN `StatusBar` module).

Does this seems like a nice solution to you?

![RPReplay_Final1605603898](https://user-images.githubusercontent.com/1902323/99375035-8a5cbf80-28c3-11eb-86c9-24cb94e72c9c.gif)

**Comment by pt7892** [comment]
Yes, something like that would've been perfect

**Comment by zoontek** [comment]
I switched to a task queue to resolve this issue: https://github.com/zoontek/react-native-bootsplash/issues/184#issuecomment-731808244

Which means your old code will work again! 🙂 (I even tried it on my iPhone)

Could you try the @next version and tell if it's ok for you?

**Comment by zoontek** [comment]
@pt7892 I switched to a task queue to resolve this issue: https://github.com/zoontek/react-native-bootsplash/issues/184#issuecomment-731808244

Which means your old code will work again! 🙂 (I even tried it on my iPhone). Except one thing… if you want to keep fading, issues **will** happen:
- If you put your app in inactive state **during** a transition, you can totally prevent the effect (see the GIF)
- When you lock your device with the app on foreground, it will fire a `show` then a `hide` on unlock (could not record a video of this one because the screen recording stop when you lock your phone 😅)

![Image from iOS](https://user-images.githubusercontent.com/1902323/99916714-fef08d80-2d0b-11eb-9b6e-b0e4047cf0d3.gif)

This happen because iOS pause your app UI changes in background, and continue to play them on foreground. Both of these issues happen on the ING app. The first one is avoidable with `react-native-bootsplash`, not the second.

```js
useEffect(() => {
  let showPending = false;

  const listener = async (state) => {
    switch (state) {
      case "active": {
        return BootSplash.hide({ fade: true })
          .then(() => console.log("hide ended"))
          .catch((error) => {
            console.log("hide error", error);
          });
      }
      case "inactive": {
        const status = await BootSplash.getVisibilityStatus();

        if (status === "visible" || showPending) {
          return;
        }

        // used to avoid enqueuing more than one show / hide cycle at the time
        showPending = true;

        return BootSplash.show({ fade: true })
          .then(() => {
            console.log("show ended");
            showPending = false;
          })
          .catch((error) => {
            console.log("show error", error);
          });
      }
    }
  };

  BootSplash.hide({ fade: true })
    .then(() => AppState.addEventListener("change", listener))
    .catch((error) => console.error(error));
  return () => {
    AppState.removeEventListener("change", listener);
  };
}, []);
```

[Bankin](https://bankin.com/) choose to avoid fading to prevent this kind of errors. That's also what I recommend:

```js
useEffect(() => {
  const listener = (state) => {
    switch (state) {
      case "active":
        return BootSplash.hide({ fade: false }).catch((error) => {
          console.log("hide error", error);
        });
      case "inactive":
        return BootSplash.show({ fade: false }).catch((error) => {
          console.log("show error", error);
        });
    }
  };

  BootSplash.hide({ fade: true })
    .then(() => AppState.addEventListener("change", listener))
    .catch((error) => console.error(error));
  return () => {
    AppState.removeEventListener("change", listener);
  };
}, []);
```

Could you try the `@next` version and tell if it's OK for you?

**Comment by pt7892** [comment]
Fade effect is not crucial feature for me, so last piece of code would be OK. Tested latest version `3.1.1`, working fine for ios, but not for android. Putting app in the background fires 'background' event and `RNBootSplash.show()` is fired, but there is no splash screen. With version `2.2.8`, it works fine

**Comment by zoontek** [comment]
@pt7892 Does the previous version worked on Android?

I found on StackOverflow that it's probably not possible: https://stackoverflow.com/a/43286180

So if you say that this worked before on Android, I would be the first surprised 😄

**Comment by pt7892** [comment]
Just tested it on emulator Pixel 3 XL API 30, works fine with `2.2.8`

**Comment by zoontek** [comment]
I just gave a shot to `2.2.8` with this code:

```js
useEffect(() => {
  BootSplash.hide({ duration: 220 });

  const listener = async (state) => {
    switch (state) {
      case "active":
        return BootSplash.hide({ duration: 220 });
      case "background":
      case "inactive":
        return BootSplash.show({ duration: 220 });
    }
  };

  AppState.addEventListener("change", listener);

  return () => {
    AppState.removeEventListener("change", listener);
  };
}, []);
```

It does not work on a physical device (Xiaomi A2, Android 10, stock android UI).
I also try without fading in / out, same result 😕

![Image from iOS](https://user-images.githubusercontent.com/1902323/99962965-57b63980-2d91-11eb-9c0b-517b58161d79.gif)

The app is paused in background, as the Android system it is supposed to do.

**Comment by zoontek** [comment]
But I confirm: it "sort of" work on emulator. Please don't rely on it, it only happen because the emulator is too slow to put the app in background.

A simple proof: by allowing a bit more CPU resources to the emulator to speed it up, we can pause the app during the fade:

<img width="627" alt="Screenshot 2020-11-23 at 13 49 40" src="https://user-images.githubusercontent.com/1902323/99964063-0444eb00-2d93-11eb-9f29-118220efc40d.png">

**Comment by pt7892** [comment]
Ah, you're right, didn't know this wasn't working on actual device... I'll check if it's possible to override `onPause` and make this happen. 
Anyway, if this latest release fixes this exception on iOS, we can close this issue. I'll check logs after we release new version of app, if it happens again, i'll reopen it.
Thx!

**Comment by zoontek** [comment]
@pt7892 I'm afraid it won't work at `onPause` too. Like the method said, it's called when the `MainActivity` is paused. Which mean you couldn't append a View in it at this time.

The only existing solution is probably https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE (and it's not customizable)

**Comment by harshmaisheri** [comment]
> I found on StackOverflow that it's probably not possible: https://stackoverflow.com/a/43286180
> 
> So if you say that this worked before on Android, I am the first surprised 😄
> 
> I will try it.

It's working fine on android devices but not on IOS devices. 
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally a view controller <UIViewController: 0x7fa79064f0a0> that is already being presented by <UIViewController: 0x7fa79220bc80>.'`

**Comment by harshmaisheri** [comment]
Did anyone got the solution?

**Comment by zoontek** [comment]
@harshmaisheri Yes, don't fade it (or an issue similar to what happen on the ING app could happen)

**Comment by harshmaisheri** [comment]
No Luck.. Still the issue is persisting ..
do i need to downgrade to `2.2.8` as mentioned above?

**Comment by niraj-khatiwada** [comment]
RNBootSplash.hide(); without giving fade property actually solves this. Not sure if this is the case for everyone.

**Comment by wswebcreation** [comment]
> RNBootSplash.hide(); without giving fade property actually solves this. Not sure if this is the case for everyone.

Yep, needed to remove the `fade` options and then it worked. I was still on `3.2.5` and upgrading to `0.64.4`. Will check later if this is fixed with a newer version
