### ISSUE TITLE
Splashscreen does not hide and throws an exception on iOS

### ISSUE THREAD

**Issue by kbrandwijk** [zoontek/react-native-bootsplash#184]
# Bug report

## Summary

Textbook implementation according to the docs. The first screen in my app attempts to hide the splashscreen. On Android, this works fine, on iOS, an error is thrown. If I manually comment out that check in the native `hide` method in the lib, everything works as expected.

```
Possible Unhandled Promise Rejection (id: 0):
Error: A bootsplash task is already pending
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 24.37 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/kim/.rvm/rubies/ruby-2.5.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: 9.0.4 - /usr/bin/javac
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.0.2

## Steps to reproduce

1. Attempt to hide the splashscreen on iOS 14.1 on a physical device, using the RN version and library version above
2. It will not hide, and throw the promise exception.
3. It doesn't matter if you try hiding in `componentDidMount`, or even later in the process (I tried  an `onLoadEnd` for an image that's shown on my main app screen).

Describe what you expected to happen:

1. The splashscreen should hide

## Reproducible sample code

I  will try to add a minimal repo over the weekend if the iOS/RN/lib version combination alone doesn't offer enough of a starting point for reproduction.

**Comment by zoontek** [comment]
@kbrandwijk Hi. Did you, by any chance, using the `show` method somewhere in your app too?

**Comment by AfrazHussain** [comment]
@kbrandwijk Please make sure you update your pods after updating to v3 of this library. I got the exact same error because I forgot to update my pods. 

To do so, you can run `cd ios && pod install` to install/update your pods.

Also @zoontek thanks a lot for this awesome library! You're a champ!

**Comment by zoontek** [comment]
I took the weekend to improve the async handling. It's now possible to queue multiple task, the promise will not throw anymore (except if the module hasn't be initialized).
Instead of relying on a statically saved pending promise, the module now rely on a task queue, which shift element in order. Which means you can **spam** the methods and do simultaneous method calls, the promises will be resolved one after the other.

A nice side effect to this change is that it allowed me to reset the module state in dev (when you reload the JS bundle), and even display the splash screen again (behind the download indicator).

Could you try it before a release? `yarn add react-native-bootsplash@next`

What happen when you try to force race conditions now:

![IMG_1172](https://user-images.githubusercontent.com/1902323/99913762-af08cb00-2cf9-11eb-8b69-86f10c436250.gif)

![IMG_1174](https://user-images.githubusercontent.com/1902323/99913757-a912ea00-2cf9-11eb-962a-f9d5c66e154e.gif)

**Comment by AlexeyVlasenko** [comment]
Suffering from the same issue :(

**Comment by zoontek** [comment]
@AlexeyVlasenko Did you read my answer ?

**Comment by AlexeyVlasenko** [comment]
> @AlexeyVlasenko Did you read my answer ?

Hi! I'm sorry. Looks like issues with XCode cache on Big Sur.
Twice build-cache reset + bundler reset fixed issue after upgrading to 3.1.0
Now all works fine!

**Comment by zoontek** [comment]
@AlexeyVlasenko https://github.com/pmadruga/react-native-clean-project is your friend 😀

**Comment by AlexeyVlasenko** [comment]
> @AlexeyVlasenko https://github.com/pmadruga/react-native-clean-project is your friend 😀

Wow! Thanks for the suggestion :)

**Comment by kbrandwijk** [comment]
Thanks for the update. I've been swamped to get a release out the door. I will most certainly try the proper fix ASAP.
