### ISSUE TITLE
Android 12 just announced splash screens why doesn't this library support it yet?

### ISSUE THREAD

**Issue by mikehardy** [zoontek/react-native-bootsplash#237]
# Feature request

https://developer.android.com/about/versions/12/features/splash-screen

I'm joking with the title of course, just giving you a heads up in case you weren't aware

Looks like it will make for faster splash loads on Android with animation and such possible

Cheers @zoontek :-) 

## Why it is needed

Because all features announced minutes earlier and available only in developer previews should be supported immediately of course. What's with this library not supporting it yet ??

**Comment by zoontek** [comment]
@mikehardy I turned angry immediately when I saw the title, well done 😄

I read about the change recently and already worked on it a bit, it's fairly complex because it rely on window background, which means this library will probably receive a major update.
My initial plan was to switch to `android:windowBackground` + `Dialog` on Android < 12, and on this for Android >= 12. It will enable easier setup on Android, but will need to be tested on brands custom UIs (it currently works well on Android AOSP, but a surprise might happen on MIUI, Samsung One, etc.)

To prevent the "jump", I will exposes constants: `statusBarHeight` and `navigationBarHeight` in order to apply negative margins and keep the logo centered when you switch to the RN handled view.

**Comment by mikehardy** [comment]
That sounds awesome.... But do you have an ETA? (still totally joking I don't even have a 12 emulator installed yet, I'm actually quite surprised you've already got experiments going!). The margin thing sound great that little jank is the only thing I see sometimes in splash screens.

**Comment by zoontek** [comment]
Sadly no ETA. I will be on holidays next week, might find time to work on it after that.

**Comment by mikehardy** [comment]
For your own mental health please don't provide ETAs for open source anyway - I was really just joking. I don't even have *space* on my disk to install the Android S preview as it is. Hope your holidays are nice !

**Comment by kuasha420** [comment]
Bruh you got me with the title, also very surprised to see @zoontek already working on it. Amazing

**Comment by mikehardy** [comment]
I feel sort of bad leaving such an awful title but @zoontek was a good sport ;-). I'm leaving it as a sort of stark parody of the toxic requests that a lot of repo maintainers do have to deal with though from users that *aren't* attempting to be funny. Maybe it will cause some self-awareness. Cheers

**Comment by Winglonelion** [comment]
Well played :)) God blessing me don't meet you in DOTA :))

**Comment by zoontek** [comment]
Work has started: https://github.com/zoontek/react-native-bootsplash/pull/243 🎉

**Comment by brunomartinezciompi** [comment]
@zoontek do you think version 4.0.0 with #243 will be available before Android 12 release? (Octobre 4 right?)

I am not trying to rush anyone just asking to see if I need to work on a workaround around this or not.

Since right now is showing first a white screen with the launcher logo before the original splash screen that this library created.

**Comment by zoontek** [comment]
@brunomartinezciompi I don't think it will, no.

**Comment by mikehardy** [comment]
Although perhaps it is possible to say that anyone could probably pick up #243 and carry it home, perhaps? (if you wrote out what the current state / leading edge of the work was...)

**Comment by drewandre** [comment]
@zoontek just curious, is there a quick way us react-native developers can get android 12 splash screens working without this lib? i.e. any android studio helpers we can use to at least get something in place? Any pointers would be nice. It’s nice to have a react native library to do all the work for you, but android studio should be able to get us up and running in time for android 12?

**Comment by zoontek** [comment]
> @zoontek just curious, is there a quick way us react-native developers can get android 12 splash screens working without this lib? i.e. any android studio helpers we can use to at least get something in place? Any pointers would be nice. It’s nice to have a react native library to do all the work for you, but android studio should be able to get us up and running in time for android 12?

You can check https://developer.android.com/about/versions/12/splash-screen-migration

**Comment by zoontek** [comment]
@mikehardy `master` now reflects `4.0.0` beta with new splash screen API usage 🎉

**Comment by mikehardy** [comment]
Oh that's fantastic @zoontek ! `<accent type="NZ">legend</accent>`
