### ISSUE TITLE
Different logo/background color for light/dark themes

### ISSUE THREAD

**Issue by Shaddix** [zoontek/react-native-bootsplash#307]
### Why it is needed?

It's a common thing to have different splash background color depending on OS theme (e.g. white background for light theme and black background for dark theme), and also different splash logos.

Is this already supported? If not, it'd be great to have this feature!

**Comment by Shaddix** [comment]
Seems like the only thing to change would be react-native.config.js, generate.ts and documentation.

If you're ok with that I could prepare a PR for this issue.

It seems to me that it'd require 2 more options for `generate-bootsplash` command:
- --dark-background-color (for dark theme background color, default to #000)
- --dark-logo (for path to the logo used for dark theme, default to '').

If --dark-logo isn't provided, nothing related to dark theme would be generated (so it's completely compatible to the current behavior).
If --dark-logo is specified, it'd generate:
### Android
- mipmap/bootsplash_logo_dark.png (for all densities)
- values-night/colors.xml (containing background color for dark theme)
- (instructions to add BootTheme to values-night/styles.xml)
### iOS
- BootSplashLogo.imageset/bootsplash_logo_dark.png (for all densities as well)
- adjust Contents.json to include dark mode images (if --dark-logo is specified)
- create colors asset (to include both dark and light background) and adjust BootSplash.storyboard to reference the color from this asset

**Comment by Shaddix** [comment]
@zoontek are you ok with adding this feature (in general)? :)

I'd completely understand if you consider this is an overcomplication/low business value.
I just wanted to know if merging a PR is a matter of time issue (I'm sure you have a lot of stuff to do) and I just need to wait and/or correct the implementation, or you disagree in general and PR won't be merged.

**Comment by zoontek** [comment]
Hi @Shaddix, and thanks for the PR! Sorry for the delay about this one.
I agree that a lot of this library users want this feature, but I'm not sure I want to merge it. Let me explain myself.

since the beginning, I received very positive feedbacks about how much time people saved / how easy it was to fix their implementation after trying so hard with _another library I won't name_. It sure feels good, but does it worth the time spent?

After shipping the v4 with the new Android `SplashScreen` API support, I added a small mention about sponsorship in the CLI tool, with one time payment available (_"It saved you a lot of time? gives 5$ to support the author!"_).
Even if I was convinced not all users would give (it's OSS after all), my expectation was what…maybe 1 per 100? Mainly from recurring users who previously use the v3 in production app, been happy with it so far and had to re-run the asset generator for Android.

I was so, so wrong. I even did [a tweet](https://twitter.com/zoontek/status/1463930213994221572) about it 😅

I have to make `react-native-bootsplash` development sustainable. A lot of the time I spend on it is used to answer to people who ask about specific usages (_"How can I do X or Y with my splash screen?"_).
Adding dark mode support out of the box feels cheap because you already made a great work in this PR, but will probably not be. I expected a whole new wave of people asking for help with specific stuff 😕

I'm not against the idea, but it will probably be an evolution of the generator.
Maybe I will drop the CLI, create a web tool to visually create your ideal splash screen. If I do it, it will have to be compatible with iOS, android and the web, will have to support dark mode, android vector assets generation, optional branding logos. And I will probably charge a one-time fee for that.

**Comment by Shaddix** [comment]
Ok, thanks for being clear!

I understand how much time it takes to support the users, and I agree that adding dark mode would probably cause more support requests.

Hope you don't mind if I keep the modified CLI in a fork?

**Comment by zoontek** [comment]
@Shaddix Not at all, it's MIT licensed after all 🙂

**Comment by Shaddix** [comment]
If anyone's interested, here's the forked CLI: https://github.com/Shaddix/react-native-bootsplash-cli-fork.

@zoontek I currently left the sponsoring message unchanged (i.e. pointing to https://github.com/sponsors/zoontek), I could remove if it bothers you.

**Comment by zoontek** [comment]
@Shaddix Please respect the initial LICENSE:

- https://github.com/Shaddix/react-native-bootsplash-cli-fork/blob/2591a2ff706213bc54b30c4d7a050f45cdd59458/LICENSE#L3
- https://github.com/Shaddix/react-native-bootsplash-cli-fork/blob/main/package.json#L6

**Comment by Shaddix** [comment]
yep, sorry, the license was autogenerated, and I automatically changed the package.json as well.

Corrected to original values

**Comment by zoontek** [comment]
@Shaddix Thanks!

**Comment by icecapp** [comment]
> …Maybe I will drop the CLI, create a web tool to visually create your ideal splash screen. If I do it, it will have to be compatible with iOS, android and the web, will have to support dark mode, android vector assets generation, optional branding logos. And I will probably charge a one-time fee for that.

+1 I'd 100% pay for such a service if it streamlines the process

**Comment by hadnet** [comment]
Nowadays dark mode is mandatory, so I don't understand why blocking to merge this fantastic PR by @Shaddix that works perfectly. So it's really sad you are thinking that way.

**Comment by milindgoel15** [comment]
It's 2023 and still no dark mode option.
