### ISSUE TITLE
Different size/color logos generated in android/app/src/main/res after migration from 3.2.6 to 4.2.3

### ISSUE THREAD

**Issue by gabriellend** [zoontek/react-native-bootsplash#376]
### Bug summary

Hello!

Not so much a bug as a migration question, sorry, wasn't sure where else to put it:

Going from 3.2.6 to 4.2.3, I needed to regenerate my assets. I did this like so:
`npx react-native generate-bootsplash assets/img/logo.png 
--background-color=212121 --assets-path=assets --flavor=main`

Most of the assets stayed the same but the ones in `android/app/src/main/res` changed. The new ones are all the same size on what looks like a transparent background (I specified a shade of black in the command above) and the old ones were different sizes on a colored background. See screen shots below for some examples. The bootsplash seems to be the same size in the app though so I don't think this is causing a problem but is this expected behavior?

![Screen Shot 2022-08-05 at 4 41 16 PM](https://user-images.githubusercontent.com/81834841/183230412-a0ba68ed-82e5-4bab-98f0-2e1679799277.png)
![Screen Shot 2022-08-05 at 4 41 02 PM](https://user-images.githubusercontent.com/81834841/183230416-24ff3dd8-1e90-47f7-9b4c-af35d2e913c3.png)
![Screen Shot 2022-08-05 at 4 41 25 PM](https://user-images.githubusercontent.com/81834841/183230417-fdbd39b0-2f0f-4e61-afd8-3f0994a4326a.png)

### Library version

4.2.3

### Environment info

```shell
System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 83.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64, android-33 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I don't think any steps are needed as this seems a pretty straightforward question.

### Reproducible sample code

```js
Same as above. Thanks very much!
```

**Comment by zoontek** [comment]
Hi @gabriellend 👋

This is a good question, but ut's totally normal (and even wanted!). Since the v4 switched to [Android SplashScreen API](https://developer.android.com/guide/topics/ui/splash-screen), the icon is now center in an image of 288x288dp (with a circle mask in it)

 _(the right one)_

![](https://developer.android.com/static/about/versions/12/images/splash-screen-icon-dimensions.png)

To preserve the `--logo-width` param logic (with default to 100px), the library CLI compute a resize ratio before generation.

So, for 100px set as `logo-width`:
- [mdpi (x1): 288px square, 100px logo](https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png)
- [hdpi (x1.5): 288 x 1.5 = 432px square, 100 x 1.5 = 150px logo](https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png)
- [xhdpi (x2): 288 x 2 = 576px square, 100 x 2 = 200px logo](https://github.com/zoontek/react-native-bootsplash/blob/master/example/android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png)
- etc.

**Comment by gabriellend** [comment]
@zoontek Thanks for your reply! So, are you saying the new logos (on the right in my screenshots) are actually different sizes even though they don't look like it?

**Comment by zoontek** [comment]
@gabriellend Before the logo could be edge to edge, now it has to be in a 288x288dp canvas 🙂 The CLI does the computation for you.

**Comment by gabriellend** [comment]
@zoontek Alright, I still don't totally get it but that's alright, it seems to be working as normal. Thanks very much!
