### ISSUE TITLE
Android logo not appearing on splash screen

### ISSUE THREAD

**Issue by matt-dalton** [zoontek/react-native-bootsplash#408]
### Bug summary

I have generated the assets using the instructions exactly (same directories etc):
```
    Assets
✨  assets/bootsplash_logo.png (120x89)
✨  assets/bootsplash_logo@2x.png (240x178)
✨  assets/bootsplash_logo@4x.png (480x355)
✨  assets/bootsplash_logo@1,5x.png (180x133)
✨  assets/bootsplash_logo@3x.png (360x266)

    Android
✏️   android/app/src/main/res/values/colors.xml
✨  android/app/src/main/res/mipmap-mdpi/bootsplash_logo.png (288x288)
✨  android/app/src/main/res/mipmap-xxxhdpi/bootsplash_logo.png (1152x1152)
✨  android/app/src/main/res/mipmap-xhdpi/bootsplash_logo.png (576x576)
✨  android/app/src/main/res/mipmap-xxhdpi/bootsplash_logo.png (864x864)
✨  android/app/src/main/res/mipmap-hdpi/bootsplash_logo.png (432x432)

    iOS
✨  ios/myapp/BootSplash.storyboard
✨  ios/myapp/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo.png (120x89)
✨  ios/myapp/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@2x.png (240x178)
✨  ios/myapp/Images.xcassets/BootSplashLogo.imageset/bootsplash_logo@3x.png (360x266)
```

I have also checked several times that I've performed all the iOS/Android setup steps exactly as documented.

However, on Android, the logo is not appearing. I can't see anything I've done wrong.

Is there anything I can do to debug this? Are there any common settings I might have that could prevent Android from finding the image?

### Library version

4.3.3

### Environment info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 42.00 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

I'm not able to share my whole codebase unfortunately - is there anything else I can add to help?

### Reproducible sample code

```js
As above
```

**Comment by zoontek** [comment]
In the README:

> ⚠️  On Android >= 12, the splash screen will not appear if you start your app from the terminal / Android Studio. To see it, kill your app and restart it in normal conditions (tap on your app icon in the app launcher).

**Comment by matt-dalton** [comment]
Sorry, I should have added, this is happening to me on a release build as well. Let me dig out some more information for you.

**Comment by zoontek** [comment]
Just in case, also in the README:

> minSdkVersion = 23 // <- AndroidX splashscreen has basic support for 21 (only the background color), so 23 is best

Basically, on Android < 6 there will be no logo.

**Comment by gabriellend** [comment]
> In the README:
> 
> > ⚠️  On Android >= 12, the splash screen will not appear if you start your app from the terminal / Android Studio. To see it, kill your app and restart it in normal conditions (tap on your app icon in the app launcher).

@zoontek Running into this as well and not quite sure what these instructions mean. Would you be able to shed some light? Are you saying to start it from the terminal/Android Studio first, then close it in the emulator, and click on the app icon in the emulator? If I try that the bootsplash does show up but the app stops running in Android Studio. Not sure where the "app icon" would be if not in the emulator or what the "app launcher" would be without Android Studio/the emulator? This might be obvious to most people. Thank you very much!

**Comment by matt-dalton** [comment]
I think that's right @gabriellend, you need to close and press the icon on the emulator

Also as a side question - the icon is not showing for me in release mode if I (for example) open a push notification. Is this also intended? Opening via the app icon shows the icon as you'd expect.

**Comment by zoontek** [comment]
@gabriellend @matt-dalton Matt is right. And same goes with notifications, yeah.

The android team say on their issue tracker that it's intended, but for me, it's clearly a bug (and it appears to be fixed on Android 13 🤨)

It also makes `setOnExitAnimationListenerˋ call unreliable: https://github.com/zoontek/react-native-bootsplash/blob/2abca66895e3323de103b9be89a15610ae89046c/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java#L144

PS: I started to experiment without AndroidX `core-splashscreen` and I successfully managed to mitigate the issue. More infos soon

**Comment by gabriellend** [comment]
@zoontek Thanks so much! What about the issue of the app stopping running when I close it in the emulator? It seems like no one else is having that issue but I thought that's just how it worked. Do I just check that the bootsplash shows up and then restart the app to actually use it? 

I also use `react-native-bootsplash` in tandem with an animated progress bar that tracks Codepush updates(see videos below). With the new version, it seems like there's no way to see everything working together because once I close the app and open it again, the Codepush download has already happened so the progress bar doesn't show. Does that seem right? If both of the above are the case I think I have to stick with an older version of `react-native-bootsplash`, so just trying to be sure. Very much appreciate your time and hopefully this might help someone else too!

This video shows the bootsplash working with Codepush at version 3.2.6. First thing you see is the bootsplash, then the same logo with an animated progress bar (the bootsplash and logo look similar but you can see the transition because the logo gets slightly bigger):

https://user-images.githubusercontent.com/81834841/218204833-5a005173-fd62-4673-a99b-0b51c3e2fdeb.MOV

This video shows what happens with version 4.5.0. As you can see, the bootsplash doesn't show at first, but the logo and animated progress bar does, then I close and open and the bootsplash shows, then the logo, but no animated progress bar:

https://user-images.githubusercontent.com/81834841/218235831-c5337b61-e311-4499-8e87-223be4dda17a.mov

**Comment by zoontek** [comment]
@gabriellend Does the logo appear when started in normal conditions? (using the app launcher).
It's probably the same issue as everyone else. Try running an Android 13 simulator to confirm if it happens too.

**Comment by gabriellend** [comment]
@zoontek Yeah, in the second video you can see that after I close it and re-open, the bootsplash and logo appear, just not the progress bar. I didn't realize there was an issue, I thought it was just a byproduct of the new version. I will try on Android 13 as well, thank you for the reminder. And thank you for the PS, I will try that too.
