### ISSUE TITLE
No logo when open app from widget

### ISSUE THREAD

**Issue by pnthach95** [zoontek/react-native-bootsplash#440]
### Bug summary

React Native Android Widget just released new version that supports open app from widget. If app is opened from widget, splash screen doesn't have logo.

https://user-images.githubusercontent.com/31266357/229999476-806fe25a-7ba1-49bf-b5f4-12df7c473f46.mp4

### Library version

4.5.3

### Environment info

```shell
System:
    OS: macOS 13.3
    CPU: (8) arm64 Apple M1
    Memory: 76.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/pnthach/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-29 | Google Play ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Clone, install dependencies, run project
2. Add widget to home screen
3. Press widget to get data
4. After finish loading, kill app
5. Press widget to open app

### Reproducible sample code

```js
https://github.com/pnthach95/KarthuriaApp
```

**Comment by zoontek** [comment]
Duplicate of https://github.com/zoontek/react-native-bootsplash/issues/408 (and others)

In the README, I mentioned:

> ⚠️  On Android >= 12, the splash screen will not appear if you start your app from the terminal / Android Studio. To see it, kill your app and restart it in normal conditions (tap on your app icon in the app launcher).

But the issue is bigger than that. Android 12 will not show the splash screen when the app is opened though an intent (Android studio, CLI, notifications, widgets, some custom app drawer). If I remember correctly, they fixed it on Android 13 (but don't give a sh*t about fixing it on Android 12…because Google)

Related:

- https://issuetracker.google.com/issues/199776339#comment3
- https://stackoverflow.com/questions/69812590/android-12-splash-screen-icon-not-displaying

I'm currently working on a new version of this library that get rid of `androidx.core:core-splashscreen` (but keep Android 12+ SplashScreen API compat…there's a trick)

**Comment by pnthach95** [comment]
I confirmed v5 fixed issue
