### ISSUE TITLE
Sync up Splash Screen Theme from App's Storage

### ISSUE THREAD

**Issue by juanchoperezj** [zoontek/react-native-bootsplash#484]
### Why it is needed?

As soon as the v5 was out I migrated from the previous version, and saw that if my app handles a local state of the theme that users chose, and the Splash Screen will use the one from the System.

This is more of a question if this could be possible. Like during/prior initialization of the Splash pass the value of the current theme of the app to avoid showing the Splash in a Theme different from the one in the app.

e.g.:
System's theme: **Dark**
App's theme: **Light**

Splash will be shown using Dark Theme.

### Possible implementation

I really want to help to achieve this, I have a bit of native language knowledge but I couldn't understand where in the code the Theme is picked up from the System.
if you can point me in some direction I could take a look and try my best.

**Comment by zoontek** [comment]
Hi @juanchoperezj 👋

The correct assets / colors are currently picked in Android `*-night` resources directories.

What you want here is (theoretically) impossible. I explain myself.

Since Android 12 and the SplashScreen API, [the system is responsible](https://developer.android.com/develop/ui/views/launch/splash-screen) of showing the splash screen **before** your app even start, using properties declared in your theme.
That's why the customisation is really limited (one logo, a brand image, a background color and that's all), but it creates the illusion that your app starts in an instant 😄

If we add such an option capability in this library, it will result in:
1. Android (the system) show your splash screen, using your Android theme
2. Your app starts, the splash screen switch from system defined mode to your custom one, following the option you added.

If these two modes (the system + your app one) doesn't match, this will result in the splash screen switching from one theme to another, like a glitch.

I *deeply* encourage you to follow system settings (same goes for preferred locales for translations), or it will create you issues like this one.

**Comment by juanchoperezj** [comment]
Hi @zoontek!

Understood, I'll close the issue since it was more like a question and you fully answered it.

Thanks!
