### ISSUE TITLE
Support more of the SplashScreen API's options (vector drawables and colors)

### ISSUE THREAD

**Issue by liamjones** [zoontek/react-native-bootsplash#491]
### Why it is needed?

Our legacy splash screen matches the display for the [the Android 12+ splash screen guidelines](https://developer.android.com/develop/ui/views/launch/splash-screen#elements) - e.g. launcher icon at a standard size on a plain background.

We'd like to migrate bootsplash from 4 to 5 to get rid of Oppo/Nokia crashes from the AndroidX splash screen library while maintaining the same setup. With the current version of 5, it looks like we'd need to generate extra bitmaps to go inside our app bundle? The old setup could reuse existing vector resources we already need for the launcher icon - these are smaller and will be drawn to the relevant resolution for the device they're displayed on.

This isn't the complete set of options the SplashScreen API supported (would it be difficult to support everything?) but the main ones for us specifically are;

* Logo can be specified as a vector drawable rather than a bitmap
* Logo background can be specified as a simple color reference rather than needing a whole drawable

### Code sample

```js
<style name="BootTheme" parent="Theme.BootSplash">
  <item name="bootSplashBackground">@color/bootsplash_background</item>
  <item name="bootSplashLogo">@drawable/bootsplash_logo</item>
  <item name="postBootSplashTheme">@style/AppTheme</item>
</style>
```

**Comment by zoontek** [comment]
@liamjones You can generate a vector drawable and use it as `bootSplashLogo` if you want, it's supported.

The background can be a simple inlined color or a color reference (default with the CLI generator), both are supported (`<item name="bootSplashBackground">@color/bootsplash_background</item>` or `<item name="bootSplashBackground">#fff</item>`)

What do you mean by generating more assets? Sure, v5 CLI supports generating assets for dark mode + brand images, but in free mode it will generates the same amount of assets as v4, just in drawable dirs instead of mipmap ones (+ will handle web support if you have an html entry point)

To be fair, v5 actually supports all SplashScreen API options, and actually even more (Google compat lib does not handle brand images for android < 12 and doesn't display the logo on android 5.x) 😄

**Comment by liamjones** [comment]
Ah, thanks for the reply. Maybe this is all just a misunderstanding on my part from the docs talking about PNG generation + [this](https://github.com/zoontek/react-native-bootsplash/blob/2fabe2cf270e72abcc9d9b960a894d880fb4875a/android/src/main/res/drawable/compat_splash_screen.xml#L9) using a bitmap tag?

> What do you mean by generating more assets?

What I meant was the docs showing `android/app/src/main/res/drawable-hdpi/bootsplash_logo.png`, etc being generated from our app logo whereas we just want to use `@drawable/ic_launcher_foreground` directly without extra PNGs being needed in the bundle.

Let me try the migration out when I have some time and I'll raise a new issue if anything seems to be impossible migrating from our v4 setup.

Apologies for wasting your time and thank you for your work on v5, it'll be nice to see the Oppo crashes gone! ❤️

**Comment by zoontek** [comment]
Yeah, the CLI generates png for the moment as I have to fork vector-drawable-tools to support them in a future version (with svg input - which is already supported)
