### ISSUE TITLE
Question about RNBootSplashActivity

### ISSUE THREAD

**Issue by krakz999** [zoontek/react-native-bootsplash#56]
### 💻 My environment

- react-native-bootsplash version: 1.2.1
- react-native version: 0.61.5
- Platform: android
- OS version: Catalina
- Device: S10+
- Simulator: no
- Android Studio version: -
- Android buildToolsVersion: -
- Xcode version: -

### 🕵️‍♂️ Question

I’m wondering what’s the purpose of RNBootSplashActivity? I tried without it, and the splash screen still appeared immediately.

**Comment by zoontek** [comment]
@krakz999 Could you provide your `android/app/src/main/res/values/styles.xml` for curiosity? 🙂

**Comment by krakz999** [comment]
> @krakz999 Could you provide your `android/app/src/main/res/values/styles.xml` for curiosity? 🙂

I have rewritten the module to inflate a layout and show that instead of showing the drawable, so I only have my AppTheme in it.

**Comment by zoontek** [comment]
`RNBootSplashActivity` exists only because RN does not currently support `android:background` property on `AppTheme`

see: https://github.com/facebook/react-native/issues/9072
and: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java#L182

**Comment by krakz999** [comment]
I've submitted a PR with my changes, it eliminates the need for a second activity. https://github.com/zoontek/react-native-bootsplash/pull/57
